server:
  port: 18080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///train
  redis:
    port: 6379
    host: 127.0.0.1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-prefix: "HDU-Train-Ticket"
