server:
  port: 18080
spring:
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql:///train
  redis:
    port: 6379
    host: 127.0.0.1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
